// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"com.gientech/equipment-data-collection/app"
	"com.gientech/equipment-data-collection/pkg/config"
	"com.gientech/equipment-data-collection/pkg/logger"
	"com.gientech/equipment-data-collection/util"
	"com.gientech/equipment-data-collection/web/controller"
)

// Injectors from wire.go:

func BuildApp(configFolder config.ConfigFolder) *app.AppContext {
	configConfig := config.NewConfig(configFolder)
	db := util.InitDB(configConfig)
	helloController := &controller.HelloController{}
	zapLogger := logger.InitLogger(configConfig)
	appContext := &app.AppContext{
		Config:   configConfig,
		DB:       db,
		HelloApi: helloController,
		Logger:   zapLogger,
	}
	return appContext
}
